server:
  port: 9100

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:9101/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:9102/
    api-service:
      path: /back/**
      url: http://127.0.0.1:8081/

shuaicj.security.jwt.secret: otherpeopledontknowit
